# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './DyberPet/MaterialSnackbar/snackBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_snackBar(object):
    def setupUi(self, snackBar):
        snackBar.setObjectName("snackBar")
        snackBar.resize(400, 70)
        snackBar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(snackBar)
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setObjectName("gridLayout")
        self.snackBarContainer = QtWidgets.QFrame(snackBar)
        self.snackBarContainer.setStyleSheet("#snackBarContainer{\n"
"    background: rgb(53,47,47);\n"
"    border: 1px solid rgb(53,47,47);\n"
"    border-radius: 5px;\n"
"}")
        self.snackBarContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.snackBarContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.snackBarContainer.setObjectName("snackBarContainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.snackBarContainer)
        self.horizontalLayout.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.supportingText = QtWidgets.QLabel(self.snackBarContainer)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.supportingText.setFont(font)
        self.supportingText.setStyleSheet("#supportingText{\n"
"    color: #f5f0f0;\n"
"    font-size: 14px;\n"
"}")
        self.supportingText.setObjectName("supportingText")
        self.horizontalLayout.addWidget(self.supportingText)
        self.action1 = QtWidgets.QPushButton(self.snackBarContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.action1.sizePolicy().hasHeightForWidth())
        self.action1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.action1.setFont(font)
        self.action1.setStyleSheet("#action1{\n"
"    background: transparent;\n"
"    color: #ffdad9;\n"
"    font-size: 14px;\n"
"}")
        self.action1.setObjectName("action1")
        self.horizontalLayout.addWidget(self.action1)
        self.action2 = QtWidgets.QPushButton(self.snackBarContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.action2.sizePolicy().hasHeightForWidth())
        self.action2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.action2.setFont(font)
        self.action2.setStyleSheet("#action2{\n"
"    background: transparent;\n"
"    color: #ffdad9;\n"
"    font-size: 14px;\n"
"}")
        self.action2.setObjectName("action2")
        self.horizontalLayout.addWidget(self.action2)
        self.closeSnackBar = QtWidgets.QPushButton(self.snackBarContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeSnackBar.sizePolicy().hasHeightForWidth())
        self.closeSnackBar.setSizePolicy(sizePolicy)
        self.closeSnackBar.setMinimumSize(QtCore.QSize(16, 16))
        self.closeSnackBar.setMaximumSize(QtCore.QSize(16, 16))
        self.closeSnackBar.setStyleSheet("#closeSnackBar{\n"
"    background: transparent;\n"
"    \n"
"    border-image: url(:/icons/resources/close.svg);\n"
"}")
        self.closeSnackBar.setText("")
        self.closeSnackBar.setObjectName("closeSnackBar")
        self.horizontalLayout.addWidget(self.closeSnackBar)
        self.gridLayout.addWidget(self.snackBarContainer, 0, 0, 1, 1)

        self.retranslateUi(snackBar)
        QtCore.QMetaObject.connectSlotsByName(snackBar)

    def retranslateUi(self, snackBar):
        _translate = QtCore.QCoreApplication.translate
        snackBar.setWindowTitle(_translate("snackBar", "snackBar"))
        self.supportingText.setText(_translate("snackBar", "Supporting Text"))
        self.action1.setText(_translate("snackBar", "Action 1"))
        self.action2.setText(_translate("snackBar", "Action 2"))
import DyberPet.MaterialSnackbar.resources
