'''
By: Marcus
Created: 2023-03-15 03: 32 P.M.
Last Modified:
Function: This file helps the program to start automatically when booting
功能：开机自启
'''

import platform
import os
import json
from DyberPet.document_path import *

self_startup_status = "off"
self_startup_application_path = ""

class checkStartupStatus():
    def checkSelfStartup(self):
        print(document_configpath)
        if os.path.isfile(document_configpath):
            # 检查是否有所需的Key
            if 'gravity' in document_configpath:
                print('Gravity detected')
            else:
                print("B")
            if 'gravityX' in document_configpath:
                print('GravityX detected')
        else:
            # 如果文件不存在，settings.py会自动创建，这里无需进行操作，且默认状态下开机自启功能为关闭状态，检查json时若没有找到该key的值
            print("[INFO] Settings.json not found, it should be generated by settings.py")

checkStartupStatus().checkSelfStartup()