# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './DyberPet/DyberPetBackup/BackupManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.dialogContainer = QtWidgets.QFrame(Form)
        self.dialogContainer.setGeometry(QtCore.QRect(12, 12, 776, 576))
        self.dialogContainer.setStyleSheet("#dialogContainer{\n"
"    border: 2px solid rgb(189,167,165);\n"
"    border-radius: 10px;\n"
"    background: rgb(241,234,235);\n"
"}")
        self.dialogContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dialogContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dialogContainer.setObjectName("dialogContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dialogContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menuBarSE = QtWidgets.QFrame(self.dialogContainer)
        self.menuBarSE.setMinimumSize(QtCore.QSize(0, 24))
        self.menuBarSE.setMaximumSize(QtCore.QSize(16777215, 24))
        self.menuBarSE.setStyleSheet("#menuBarSE{\n"
"    background: rgb(241,234,235);\n"
"    border: 1px solid rgb(241,234,235);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}")
        self.menuBarSE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuBarSE.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuBarSE.setObjectName("menuBarSE")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.menuBarSE)
        self.horizontalLayout_2.setContentsMargins(24, 0, 24, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(623, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.closeApp = QtWidgets.QPushButton(self.menuBarSE)
        self.closeApp.setMinimumSize(QtCore.QSize(16, 16))
        self.closeApp.setMaximumSize(QtCore.QSize(16, 16))
        self.closeApp.setStyleSheet("QPushButton{\n"
"    background: rgb(241,234,235);\n"
"    border: 0px solid rgb(241,234,235);\n"
"    border-radius: 5px;\n"
"    color: #534343;\n"
"    font-size: 14px;\n"
"    border-image: url(:/icons/res/close.svg);\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"    font-weight: bold;\n"
"    background: rgb(231,226,226);\n"
"    color: #211a1a;\n"
"}\n"
"\n"
"QPushButton:Pressed{\n"
"    font-weight: bold;\n"
"    background: #ffdad9;\n"
"    color: #2d1516;\n"
"}\n"
"")
        self.closeApp.setText("")
        self.closeApp.setObjectName("closeApp")
        self.horizontalLayout_2.addWidget(self.closeApp)
        self.verticalLayout.addWidget(self.menuBarSE)
        self.titleBar = QtWidgets.QFrame(self.dialogContainer)
        self.titleBar.setMinimumSize(QtCore.QSize(0, 64))
        self.titleBar.setMaximumSize(QtCore.QSize(16777215, 64))
        self.titleBar.setStyleSheet("#titleBar{\n"
"    background: rgb(241,234,235);\n"
"    border: 1px solid rgb(241,234,235);\n"
"}")
        self.titleBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleBar)
        self.horizontalLayout.setContentsMargins(24, -1, 24, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(275, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.appTitle = QtWidgets.QLabel(self.titleBar)
        self.appTitle.setStyleSheet("#appTitle{\n"
"    font-size: 16px;\n"
"    color: #1f1f1f;\n"
"    font-weight: bold;\n"
"    background: transparent;\n"
"}")
        self.appTitle.setObjectName("appTitle")
        self.horizontalLayout.addWidget(self.appTitle)
        spacerItem2 = QtWidgets.QSpacerItem(275, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.titleBar)
        self.appContainer = QtWidgets.QFrame(self.dialogContainer)
        self.appContainer.setEnabled(True)
        self.appContainer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.appContainer.setStyleSheet("#appContainer{\n"
"    background: #fff;\n"
"    border: 0px solid #fff;\n"
"}")
        self.appContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appContainer.setObjectName("appContainer")
        self.gridLayout = QtWidgets.QGridLayout(self.appContainer)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.appFrame = QtWidgets.QStackedWidget(self.appContainer)
        self.appFrame.setStyleSheet("#appFrame{\n"
"    background: #fff;\n"
"    border: 1px solid #fff;\n"
"}")
        self.appFrame.setObjectName("appFrame")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.savesDesc = QtWidgets.QLabel(self.page)
        self.savesDesc.setStyleSheet("QLabel{\n"
"    font-size: 14px;\n"
"    color: #211a1a\n"
"}")
        self.savesDesc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.savesDesc.setWordWrap(True)
        self.savesDesc.setObjectName("savesDesc")
        self.verticalLayout_4.addWidget(self.savesDesc)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.setSaveModeRead = QtWidgets.QPushButton(self.page)
        self.setSaveModeRead.setMinimumSize(QtCore.QSize(0, 24))
        self.setSaveModeRead.setMaximumSize(QtCore.QSize(16777215, 24))
        self.setSaveModeRead.setStyleSheet("QPushButton{\n"
"    background: rgb(241,234,235);\n"
"    border: 0px solid rgb(241,234,235);\n"
"    border-radius: 5px;\n"
"    color: #534343;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"    font-weight: bold;\n"
"    background: rgb(231,226,226);\n"
"    color: #211a1a;\n"
"}\n"
"\n"
"QPushButton:Pressed{\n"
"    font-weight: bold;\n"
"    background: #ffdad9;\n"
"    color: #2d1516;\n"
"}\n"
"\n"
"QPushButton:Checked{\n"
"    font-weight: bold;\n"
"    background: #ffdad9;\n"
"    color: #2d1516;\n"
"}")
        self.setSaveModeRead.setCheckable(True)
        self.setSaveModeRead.setChecked(False)
        self.setSaveModeRead.setObjectName("setSaveModeRead")
        self.horizontalLayout_6.addWidget(self.setSaveModeRead)
        self.setSaveModeWrite = QtWidgets.QPushButton(self.page)
        self.setSaveModeWrite.setMinimumSize(QtCore.QSize(0, 24))
        self.setSaveModeWrite.setMaximumSize(QtCore.QSize(16777215, 24))
        self.setSaveModeWrite.setStyleSheet("QPushButton{\n"
"    background: rgb(241,234,235);\n"
"    border: 0px solid rgb(241,234,235);\n"
"    border-radius: 5px;\n"
"    color: #534343;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"    font-weight: bold;\n"
"    background: rgb(231,226,226);\n"
"    color: #211a1a;\n"
"}\n"
"\n"
"QPushButton:Pressed{\n"
"    font-weight: bold;\n"
"    background: #ffdad9;\n"
"    color: #2d1516;\n"
"}\n"
"\n"
"QPushButton:Checked{\n"
"    font-weight: bold;\n"
"    background: #ffdad9;\n"
"    color: #2d1516;\n"
"}")
        self.setSaveModeWrite.setCheckable(True)
        self.setSaveModeWrite.setChecked(True)
        self.setSaveModeWrite.setObjectName("setSaveModeWrite")
        self.horizontalLayout_6.addWidget(self.setSaveModeWrite)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.saveSlot1 = QtWidgets.QPushButton(self.page)
        self.saveSlot1.setMinimumSize(QtCore.QSize(0, 32))
        self.saveSlot1.setMaximumSize(QtCore.QSize(16777215, 32))
        self.saveSlot1.setStyleSheet("QPushButton{\n"
"    background: rgb(241,234,235);\n"
"    border: 0px solid rgb(241,234,235);\n"
"    border-radius: 5px;\n"
"    color: #534343;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"    font-weight: bold;\n"
"    background: rgb(231,226,226);\n"
"    color: #211a1a;\n"
"}\n"
"\n"
"QPushButton:Pressed{\n"
"    font-weight: bold;\n"
"    background: #ffdad9;\n"
"    color: #2d1516;\n"
"}\n"
"\n"
"QPushButton:Checked{\n"
"    font-weight: bold;\n"
"    background: #ffdad9;\n"
"    color: #2d1516;\n"
"}")
        self.saveSlot1.setObjectName("saveSlot1")
        self.verticalLayout_4.addWidget(self.saveSlot1)
        self.saveSlot2 = QtWidgets.QPushButton(self.page)
        self.saveSlot2.setMinimumSize(QtCore.QSize(0, 32))
        self.saveSlot2.setMaximumSize(QtCore.QSize(16777215, 32))
        self.saveSlot2.setStyleSheet("QPushButton{\n"
"    background: rgb(241,234,235);\n"
"    border: 0px solid rgb(241,234,235);\n"
"    border-radius: 5px;\n"
"    color: #534343;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"    font-weight: bold;\n"
"    background: rgb(231,226,226);\n"
"    color: #211a1a;\n"
"}\n"
"\n"
"QPushButton:Pressed{\n"
"    font-weight: bold;\n"
"    background: #ffdad9;\n"
"    color: #2d1516;\n"
"}\n"
"\n"
"QPushButton:Checked{\n"
"    font-weight: bold;\n"
"    background: #ffdad9;\n"
"    color: #2d1516;\n"
"}")
        self.saveSlot2.setObjectName("saveSlot2")
        self.verticalLayout_4.addWidget(self.saveSlot2)
        self.saveSlot3 = QtWidgets.QPushButton(self.page)
        self.saveSlot3.setMinimumSize(QtCore.QSize(0, 32))
        self.saveSlot3.setMaximumSize(QtCore.QSize(16777215, 32))
        self.saveSlot3.setStyleSheet("QPushButton{\n"
"    background: rgb(241,234,235);\n"
"    border: 0px solid rgb(241,234,235);\n"
"    border-radius: 5px;\n"
"    color: #534343;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"    font-weight: bold;\n"
"    background: rgb(231,226,226);\n"
"    color: #211a1a;\n"
"}\n"
"\n"
"QPushButton:Pressed{\n"
"    font-weight: bold;\n"
"    background: #ffdad9;\n"
"    color: #2d1516;\n"
"}\n"
"\n"
"QPushButton:Checked{\n"
"    font-weight: bold;\n"
"    background: #ffdad9;\n"
"    color: #2d1516;\n"
"}")
        self.saveSlot3.setObjectName("saveSlot3")
        self.verticalLayout_4.addWidget(self.saveSlot3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 186, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.appFrame.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.appFrame.addWidget(self.page_2)
        self.gridLayout.addWidget(self.appFrame, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.appContainer)
        self.navBar = QtWidgets.QFrame(self.dialogContainer)
        self.navBar.setMinimumSize(QtCore.QSize(0, 64))
        self.navBar.setMaximumSize(QtCore.QSize(16777215, 64))
        self.navBar.setStyleSheet("#navBar{\n"
"    background: #f5f0f0;\n"
"    border: 1px solid #f5f0f0;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}")
        self.navBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navBar.setObjectName("navBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.navBar)
        self.horizontalLayout_5.setContentsMargins(24, 9, 24, 9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(163, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.savesNavBarContainer = QtWidgets.QFrame(self.navBar)
        self.savesNavBarContainer.setMinimumSize(QtCore.QSize(64, 24))
        self.savesNavBarContainer.setMaximumSize(QtCore.QSize(64, 24))
        self.savesNavBarContainer.setStyleSheet("#savesNavBarContainer{\n"
"    background: #ffdad9;\n"
"    border: 0px solid #ffdad9;\n"
"    border-radius: 12px;\n"
"}")
        self.savesNavBarContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.savesNavBarContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.savesNavBarContainer.setObjectName("savesNavBarContainer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.savesNavBarContainer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.savesNavBarIcon = QtWidgets.QPushButton(self.savesNavBarContainer)
        self.savesNavBarIcon.setMinimumSize(QtCore.QSize(16, 16))
        self.savesNavBarIcon.setMaximumSize(QtCore.QSize(16, 16))
        self.savesNavBarIcon.setStyleSheet("#savesNavBarIcon{\n"
"    background: transparent;\n"
"    border-image: url(:/icons/res/save_selected.svg);\n"
"}")
        self.savesNavBarIcon.setText("")
        self.savesNavBarIcon.setObjectName("savesNavBarIcon")
        self.horizontalLayout_3.addWidget(self.savesNavBarIcon)
        spacerItem6 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addWidget(self.savesNavBarContainer)
        self.savesNavBarText = QtWidgets.QPushButton(self.navBar)
        self.savesNavBarText.setMinimumSize(QtCore.QSize(64, 0))
        self.savesNavBarText.setMaximumSize(QtCore.QSize(64, 16777215))
        self.savesNavBarText.setStyleSheet("#savesNavBarText{\n"
"    background: transparent;\n"
"    border: 0px solid #fff;\n"
"    color: #2d1516;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}")
        self.savesNavBarText.setObjectName("savesNavBarText")
        self.verticalLayout_2.addWidget(self.savesNavBarText)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(163, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.backupNavBarContainer = QtWidgets.QFrame(self.navBar)
        self.backupNavBarContainer.setMinimumSize(QtCore.QSize(64, 24))
        self.backupNavBarContainer.setMaximumSize(QtCore.QSize(64, 24))
        self.backupNavBarContainer.setStyleSheet("#backupNavBarContainer{\n"
"    background: transparent;\n"
"    border: 0px solid #ffdad9;\n"
"    border-radius: 12px;\n"
"}")
        self.backupNavBarContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backupNavBarContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backupNavBarContainer.setObjectName("backupNavBarContainer")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.backupNavBarContainer)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.backupNavBarIcon = QtWidgets.QPushButton(self.backupNavBarContainer)
        self.backupNavBarIcon.setMinimumSize(QtCore.QSize(16, 16))
        self.backupNavBarIcon.setMaximumSize(QtCore.QSize(16, 16))
        self.backupNavBarIcon.setStyleSheet("#backupNavBarIcon{\n"
"    background: transparent;\n"
"    border-image: url(:/icons/res/backup.svg);\n"
"}")
        self.backupNavBarIcon.setText("")
        self.backupNavBarIcon.setObjectName("backupNavBarIcon")
        self.horizontalLayout_4.addWidget(self.backupNavBarIcon)
        spacerItem9 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_3.addWidget(self.backupNavBarContainer)
        self.backupNavBarText = QtWidgets.QPushButton(self.navBar)
        self.backupNavBarText.setMinimumSize(QtCore.QSize(64, 0))
        self.backupNavBarText.setMaximumSize(QtCore.QSize(64, 16777215))
        self.backupNavBarText.setStyleSheet("#backupNavBarText{\n"
"    background: transparent;\n"
"    border: 0px solid #fff;\n"
"    color: #2d1516;\n"
"    font-size: 12px;\n"
"}")
        self.backupNavBarText.setObjectName("backupNavBarText")
        self.verticalLayout_3.addWidget(self.backupNavBarText)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem10 = QtWidgets.QSpacerItem(163, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.verticalLayout.addWidget(self.navBar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.appTitle.setText(_translate("Form", "存档与备份"))
        self.savesDesc.setText(_translate("Form", "「存档」功能会把当前的用户数据保存至程序工作目录以外的地方。在macOS版中我们强烈推荐您在更新前进行存档，因为更新会覆盖掉原有的用户数据，若您有存档则可轻松恢复您的桌宠数据。"))
        self.setSaveModeRead.setText(_translate("Form", "读取"))
        self.setSaveModeWrite.setText(_translate("Form", "保存"))
        self.saveSlot1.setText(_translate("Form", "存档1"))
        self.saveSlot2.setText(_translate("Form", "存档2"))
        self.saveSlot3.setText(_translate("Form", "存档3"))
        self.savesNavBarText.setText(_translate("Form", "存档"))
        self.backupNavBarText.setText(_translate("Form", "备份"))
import DyberPet.DyberPetBackup.Resources
